INSERT INTO cities_canada_usa
VALUES (1, 44, 'Collingswood', 'Kollingsvud,kalyngswwd, nywjrsy,Коллингсвуд,کالینگسوود، نیوجرسی', 39.91817, -75.07128, 'Collingswood', 'PPL', 'US', 'C', 'P', 007, 'PPL',
        'PPL',
        'NJ',
        9,
        10,
        'America/New_York',
        '2011-05-14',
        13926
       );
INSERT INTO cities_canada_usa
VALUES (2,
        45,
        'Collingswaod',
        'Kollingsvud,kalyngswwd, nywjrsy,Коллингсвуд,کالینگسوود، نیوجرسی',
        39.91817,-75.07128,
        'Collingswaod',
        'PPL',
        'US',
        'G',
        'P',
        007,
        'SS',
        'TT',
        'NJ',
        9,
        10,
        'America/New_York',
        '2011-05-14',
        13926);
INSERT INTO cities_canada_usa
VALUES (3,
        46,
        'Collings',
        'Kollingsvud,kalyngswwd, nywjrsy,Коллингсвуд,کالینگسوود، نیوجرسی',
        39.91817,-75.07128,
        'Collings',
        'PPL',
        'CA',
        'G',
        'P',
        007,
        'D',
        'R',
        'NJ',
        9,
        10,
        'America/New_York',
        '2011-05-14',
        13926);
INSERT INTO cities_canada_usa
VALUES (4,
        47,
        'Callingswood',
        'Kollingsvud,kalyngswwd, nywjrsy,Коллингсвуд,کالینگسوود، نیوجرسی',
        39.91817,-75.07128,
        'Callingswood',
        'PPL',
        'RF',
        'M',
        'P',
        007,
        'D',
        'T',
        'NJ',
        9,
        10,
        'America/New_York',
        '2011-05-14',
        13926);